name: build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: "echo 'something'"
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk

    - uses: actions/upload-artifact@v4
      with:
        name: picos.apk
        path: build/app/outputs/flutter-apk/app-release.apk
